### ISSUE TITLE
how to creat domain in GAN

### ISSUE THREAD

**Issue by chenlihuang** [aaleotti-unimore/adversarial_DGA#1]
which pyfile can I get GAN domains? and could you describe the structure of this project

**Comment by chenlihuang** [comment]
@aaleotti-unimore

**Comment by aaleotti-unimore** [comment]
Hi, sorry this is not initially meant to be a user friendly interface. as soon I have free time for this project I will add a README to describe the project. you can find the main file in dga_gan.py
